const products = [
    {
        id: 0,
        name: "Nike Air Max",
        brand: "Nike",
        price: 120,
        color: "Black",
        size: "10",
        qty: 0,
        image: require("../images/shoes_2.jpg"),
    },
    {
        id: 1,
        name: "Adidas Ultraboost",
        brand: "Adidas",
        price: 140,
        color: "White",
        size: "9",
        qty: 0,
        image: require("../images/shoes_3.jpg"),
    },
    {
        id: 2,
        name: "Puma RS-X",
        brand: "Puma",
        price: 110,
        color: "Red",
        size: "11",
        qty: 0,
        image: require("../images/shoes_4.jpg"),
    },
    {
        id: 3,
        name: "New Balance 990v5",
        brand: "New Balance",
        price: 150,
        color: "Grey",
        size: "9.5",
        qty: 0,
        image: require("../images/shoes_5.jpg"),
    },
    {
        id: 4,
        name: "Reebok Classic Leather",
        brand: "Reebok",
        price: 95,
        color: "White",
        size: "8",
        qty: 0,
        image: require("../images/shoes_6.jpg"),
    },
    {
        id: 5,
        name: "Vans Old Skool",
        brand: "Vans",
        price: 70,
        color: "Black/White",
        size: "10",
        qty: 0,
        image: require("../images/shoes_7.jpg"),
    },
    {
        id: 6,
        name: "Converse Chuck Taylor All Star",
        brand: "Converse",
        price: 55,
        color: "Navy Blue",
        size: "7",
        qty: 0,
        image: require("../images/shoes_1.jpg"),
    },
];

export default products;
