const products = [
    {
        id: 0,
        name: "Nike Air Max",
        brand: "Nike",
        price: 120,
        discountedPrice: 99,
        color: "Black",
        size: "10",
        qty: 0,
        image: require("../images/shoes_2.jpg"),
        description: "High-quality running shoes with air cushioning.",
        category: "Footwear",
        rating: 4.5,
        createdDate: "2023-09-18",
        updatedDate: "2023-09-18",
    },
    {
        id: 1,
        name: "Adidas Ultraboost",
        brand: "Adidas",
        price: 140,
        discountedPrice: null, // No discount for this product
        color: "White",
        size: "9",
        qty: 0,
        image: require("../images/shoes_3.jpg"),
        description: "Premium running shoes with Boost technology.",
        category: "Footwear",
        rating: 4.8,
        createdDate: "2023-09-18",
        updatedDate: "2023-09-18",
    },
    {
        id: 2,
        name: "Puma RS-X",
        brand: "Puma",
        price: 110,
        discountedPrice: 89, 
        color: "Red",
        size: "11",
        qty: 0,
        image: require("../images/shoes_4.jpg"),
        description: "Fashionable and comfortable sneakers.",
        category: "Footwear",
        rating: 4.3,
        createdDate: "2023-09-18",
        updatedDate: "2023-09-18",
    },
    {
        id: 3,
        name: "New Balance 990v5",
        brand: "New Balance",
        price: 150,
        discountedPrice: null,
        color: "Grey",
        size: "9.5",
        qty: 0,
        image: require("../images/shoes_5.jpg"),
        description: "Classic style with modern comfort.",
        category: "Footwear",
        rating: 4.7,
        createdDate: "2023-09-18",
        updatedDate: "2023-09-18",
    },
    {
        id: 4,
        name: "Reebok Classic Leather",
        brand: "Reebok",
        price: 95,
        discountedPrice: null,
        color: "White",
        size: "8",
        qty: 0,
        image: require("../images/shoes_6.jpg"),
        description: "Timeless and versatile sneakers.",
        category: "Footwear",
        rating: 4.2,
        createdDate: "2023-09-18",
        updatedDate: "2023-09-18",
    },
    {
        id: 5,
        name: "Vans Old Skool",
        brand: "Vans",
        price: 70,
        discountedPrice: 59, // Discounted price
        color: "Black/White",
        size: "10",
        qty: 0,
        image: require("../images/shoes_7.jpg"),
        description: "Iconic skateboarding shoes.",
        category: "Footwear",
        rating: 4.6,
        createdDate: "2023-09-18",
        updatedDate: "2023-09-18",
    },
    {
        id: 6,
        name: "Converse Chuck Taylor All Star",
        brand: "Converse",
        price: 55,
        discountedPrice: null,
        color: "Navy Blue",
        size: "7",
        qty: 0,
        image: require("../images/shoes_1.jpg"),
        description: "Classic canvas sneakers.",
        category: "Footwear",
        rating: 4.4,
        createdDate: "2023-09-18",
        updatedDate: "2023-09-18",
    },
];

export default products;
